apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-backend-deployment
  labels:
    app: sns-backend
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: sns-backend-app
  template:
    metadata:
      labels:
        app: sns-backend-app
    spec:
      containers:
      - name: sns-backend
        image: sns-backend
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
